server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/pet?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=true
    username: root
    password: zX20010411ok
  servlet:
    multipart:
      max-file-size: 10MB #单个文件的大小
      max-request-size: 100MB # 整个请求要求的大小
  application:
    name: user
  cloud:
    nacos:
        discovery:
          server-addr: 124.220.205.34:8848/nacos #nacos地址
  # REDIS (RedisProperties)
  data:
    redis:
      # Redis数据库索引（默认为0）
      database: 0
      # Redis服务器地址
      host: 124.220.205.34
      # Redis服务器连接端口
      port: 6379
      # Redis服务器连接密码（默认为空）
      password: zX20010411ok
      # 连接超时时间（毫秒）
      timeout: 1000
      username: default
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0


